apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  type: ClusterIP
  ports:
    - targetport: 80 #port where the backend is exposed
      port: 80 # port where the ip is exposed
    
  selector:
    app: myapp
    type: back-end
          
